### ISSUE TITLE
bugs when try to make target pictures

### ISSUE THREAD

**Issue by APotatoBoy** [Kuzphi/EverybodyDanceNow-Temporal-FaceGAN#1]
Hello, when I tryed to make taget pictures,errors occured.
I run 'python target.py --name 2',because the form of the anno is '2_000000000001_keypoints.json'.
The erros are as follows:
Traceback (most recent call last):
  File "/home/edward/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/edward/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "target.py", line 30, in gao
    anno[key] = np.array(anno[key]).reshape(-1, 3)
ValueError: cannot reshape array of size 1 into shape (3)

**Comment by Kuzphi** [comment]
could you provide the information in 2_000000000001_keypoints.json?

**Comment by Janekaka** [comment]
I have the same problem, have you solved it?

**Comment by vansondang** [comment]
I got same probleam

**Comment by talatccan** [comment]
I had same problem and solved it.

It's because person_id key is int. So i modify the code as below in target.py and source.py:
```
	temp_dict = anno.copy()
	anno.pop('person_id')
	for key in anno:
		# print(key)
		anno[key] = np.array(anno[key]).reshape(-1, 3)
		anno[key][:,  0] -= 420
		# print(anno[key][:,  0].min())
		anno[key][:, :2]  = (anno[key][:, :2] / 1080. * 512).clip(min=0)
	anno['person_id'] = temp_dict['person_id']
```
