### ISSUE TITLE
the lost of the txt file:FileNotFoundError: [Errno 2] No such file or directory: './data/2/train/scale.txt'

### ISSUE THREAD

**Issue by aszxnm** [Kuzphi/EverybodyDanceNow-Temporal-FaceGAN#3]
Hello,I want to have a try with your code.
Traceback (most recent call last):
  File "source.py", line 159, in <module>
    f = open("./data/%s/train/scale.txt"%args.which_train,'r')
FileNotFoundError: [Errno 2] No such file or directory: './data/2/train/scale.txt'
no scale.txt file in this folder.
Is this build automately?

**Comment by kjzju** [comment]
I met the same problem, how do you solve this problem?Thx

**Comment by talatccan** [comment]
I've solved it.

In target.py you will see the comment lines. Just modify it and it will work.
